
#zsh
cd `dirname $0`

## path of profile
PROFILE_TOPPICKUPNAME=etc/profile_topPickUpName.txt
PROFILE_BOTTOMPICKUPNAME=etc/profile_bottomPickUpName.txt
PROFILE_MULTINAME=etc/profile_multiName.txt

## num of line
RANGE_OF_TARGET_RANK=10
NUM_OF_TOP_NAME=`wc -l < $PROFILE_TOPPICKUPNAME`
NUM_OF_TOP_NAME=`expr $NUM_OF_TOP_NAME + 1`

## startline
TIMESTAMP=1
START_OF_TOP_PICKUP_NAME=3
END_OF_TOP_PICKUP_NAME=`expr $START_OF_TOP_PICKUP_NAME + $NUM_OF_TOP_NAME \* 3 - 1`
START_OF_RANKING=`expr $END_OF_TOP_PICKUP_NAME + 3`
END_OF_RANKING=`expr $START_OF_RANKING + $RANGE_OF_TARGET_RANK - 1`
#,2015/11/11 06:48:05
#pickUpTU
#Mu, ,
#,,
#,,
#:
#pickUpRank
#ranking
#1,1502,Mumin�J??


CONFIG_FILE=config.txt
echo PROFILE_TOPPICKUPNAME=$PROFILE_TOPPICKUPNAME >$CONFIG_FILE
echo PROFILE_BOTTOMPICKUPNAME=$PROFILE_BOTTOMPICKUPNAME >>$CONFIG_FILE
echo PROFILE_MULTINAME=$PROFILE_MULTINAME >>$CONFIG_FILE
echo RANGE_OF_TARGET_RANK=$RANGE_OF_TARGET_RANK >>$CONFIG_FILE
echo NUM_OF_TOP_NAME=$NUM_OF_TOP_NAME >>$CONFIG_FILE
echo TIMESTAMP=$TIMESTAMP >>$CONFIG_FILE
echo START_OF_TOP_PICKUP_NAME=$START_OF_TOP_PICKUP_NAME >>$CONFIG_FILE
echo END_OF_TOP_PICKUP_NAME=$END_OF_TOP_PICKUP_NAME >>$CONFIG_FILE
echo START_OF_RANKING=$START_OF_RANKING >>$CONFIG_FILE
echo END_OF_RANKING=$END_OF_RANKING >>$CONFIG_FILE
